# Generated by Django 4.2.5 on 2023-10-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_category_slug_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='cats', through='mainapp.PostCategory', to='mainapp.category', verbose_name='Категория'),
        ),
    ]
