# Generated by Django 4.2.5 on 2023-10-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='post_per_day',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
